
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 2;
  public static final int DORMIR = 11;
  public static final int LETRA = 4;
  public static final int INICIO = 7;
  public static final int FIN = 8;
  public static final int EOF = 0;
  public static final int NUMERO = 14;
  public static final int PARIZQ = 3;
  public static final int ID = 13;
  public static final int error = 1;
  public static final int DIBUJARCARA = 9;
  public static final int ELIMINARCARA = 10;
  public static final int Programa = 6;
  public static final int PARDER = 5;
  public static final int CAMBIARMODO = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "PARIZQ",
  "LETRA",
  "PARDER",
  "Programa",
  "INICIO",
  "FIN",
  "DIBUJARCARA",
  "ELIMINARCARA",
  "DORMIR",
  "CAMBIARMODO",
  "ID",
  "NUMERO"
  };
}

