
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIBUJARCARA = 14;
  public static final int NEUTRAL = 5;
  public static final int CAMBIARMODO = 17;
  public static final int LETRA = 9;
  public static final int PARIZQ = 8;
  public static final int PARDER = 10;
  public static final int DORMIR = 16;
  public static final int DORMIDA = 4;
  public static final int ID = 18;
  public static final int Programa = 11;
  public static final int FELIZ = 6;
  public static final int ENOJADA = 3;
  public static final int COMA = 7;
  public static final int ELIMINARCARA = 15;
  public static final int EOF = 0;
  public static final int TRISTE = 2;
  public static final int NUMERO = 19;
  public static final int error = 1;
  public static final int FIN = 13;
  public static final int INICIO = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRISTE",
  "ENOJADA",
  "DORMIDA",
  "NEUTRAL",
  "FELIZ",
  "COMA",
  "PARIZQ",
  "LETRA",
  "PARDER",
  "Programa",
  "INICIO",
  "FIN",
  "DIBUJARCARA",
  "ELIMINARCARA",
  "DORMIR",
  "CAMBIARMODO",
  "ID",
  "NUMERO"
  };
}

